server:
  port: 8080
redis:
  host: localhost
  port: 6379
  timeout: 30
  pool_size: 10

logger:
  env: prod
  level: INFO
  encoding: console
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
